Add resources, utilities directory, AsciiArtReader class
warofants/wwa pull request #114
Opened 2019-09-04 23:59 UTC by TrainingAfternoon

Added the resources and utilities directory, and the AsciiArtReader class that will read .txts from resources/art and return the content as a String. Modified the show title command to use this functionality

2019-09-05 02:07 UTC, Plat251 requested changes
I have a feeling that this needs a rebase, because it proposes changes that are already incorporated. That makes reviewing it very difficult.

2019-09-05 02:07 UTC, Plat251 commented on src/main/java/com/worldwarofants/game/utils/AsciiArtReader.java
> +                )
This could be condensed and cleaned up into fewer lines with a more consistent indentation and newline style.
```java
        //try-with-resources is declared
        try (
             InputStreamReader fileReader = new InputStreamReader(classLoader
                                                                  .getResourceAsStream(completeFileName)
            )
```

2019-09-05 12:06 UTC, Veradux commented
Yeah I have no idea how you managed this, but if you could make it so only your changes appear in the `files changed` tab, that would be great.

2019-09-05 14:23 UTC, Veradux commented on src/main/java/com/worldwarofants/game/utils/AsciiArtReader.java
> +                )
Maybe I'm not seeing what you're talking about but.. isn't the code in both the same number of lines?

2019-09-05 19:57 UTC, Plat251 commented on src/main/java/com/worldwarofants/game/utils/AsciiArtReader.java
> +                )
It is very mildly reorganized, with comment in a more logical location and a less disruptive newline.

2019-09-09 10:40 UTC, Veradux requested changes
This looks like it needs a lot of work still, before it can be approved. Try to not make PRs with unfinished code, like all of those empty classes.

2019-09-09 10:40 UTC, Veradux commented on src/main/java/com/worldwarofants/game/module/ModuleName.java
> +    ANTS
* Am I blind or does an ANTS module class not exist in this PR? 

* Isn't that completely out of scope for this PR in general? I don't think an ascii reader feature should have any relations with game models.

* Having an ANTS module doesn't really make much sense. Modules should define different "screens" of the game.

2019-09-09 10:40 UTC, Veradux commented on src/main/java/com/worldwarofants/game/module/ants/arch/AntGroupController.java
> +public class AntGroupController {
What's the point of this? Also it doesn't extend the abstract classes.

2019-09-09 10:40 UTC, Veradux commented on src/main/java/com/worldwarofants/game/module/ants/arch/AntGroupView.java
> +public class AntGroupView {
What's the point of this? Also it doesn't extend the abstract classes.

2019-09-09 10:40 UTC, Veradux commented on src/main/java/com/worldwarofants/game/module/examplefeature/utils/ExampleUtils.java
> +            "This is the package where I would put my com.worldwarofants.game.utils classes, IF I HAD ANY! (ಠ益ಠ)";
Why was this change made?

2019-09-09 10:40 UTC, Veradux commented on src/main/java/com/worldwarofants/game/module/utils/AsciiArtReader.java
> +
What's the point of adding an empty constructor? Classes automatically have this, even if you don't write it.

2019-09-09 10:40 UTC, Veradux commented on src/main/resources/antspecies/Species.yml
> +example_ant:
Where is this file used, in this PR?

2019-09-09 10:40 UTC, Veradux commented on src/main/java/com/worldwarofants/game/module/utils/AsciiArtReader.java
> +             * art is returned */
The word 'art' is repeated twice.

2019-09-24 17:42 UTC, closed without merging